version: "3.9"

services:
  db_login:
    build:
      dockerfile: ./docker/db.dockerfile
      context: .
    image: login_database:v1
    container_name: database_login
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    networks:
      - nwlogin
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./init_db:/docker-entrypoint-initdb.d/

  api_login:
    build:
      dockerfile: ./docker/api.dockerfile
      context: .
    image: login_api:v1
    container_name: api_login
    command: sh -c "python main.py"
    env_file:
      - .env
    depends_on:
      - db_login
    ports:
      - 8000:8000
    networks:
      - nwlogin
    volumes:
      - ./logs:/var/www/logs

  pgadmin:
    build:
      dockerfile: ./docker/pgadmin.dockerfile
      context: .
    image: pgadmin_db:v1
    container_name: pgadmin_db
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db_login
    networks:
      - nwlogin

networks:
  nwlogin:
    name: "nwlogin"
    driver: "bridge"
volumes:
  pgdata:
