from __future__ import annotations

from typing import Protocol

from contexts.identity_access.domain.entities.role import Role
from contexts.identity_access.domain.entities.user import User


class UserRepository(Protocol):
    async def get_by_id(self, user_id: int, *, active_only: bool = True) -> User | None: ...

    async def get_by_cpf(self, cpf: str) -> User | None: ...

    async def get_by_email(self, email: str, *, active_only: bool = True) -> User | None: ...

    async def get_by_reset_token(self, token: str) -> User | None: ...

    async def list_active(self) -> list[User]: ...

    async def add(self, user: User) -> User: ...

    async def save(self, user: User) -> User: ...
